EnableAnimalNaturalSpawning: false
ShipmentBox:
  Crops:
    Spring:
      - POTATOE,100
      - WHEAT,25
    Summer:
      - PUMPKIN,50
      - MELON,50
      - WHEAT,25
    Autumn:
      - BEETROOT,100
      - WHEAT,25
    Winter:
      - BEETROOT,100
  Items:
    - COBBLESTONE,2
